site_name: 'KnitPkg Documentation'
site_description: 'A modern package & project manager for MQL5/MQL4'
site_url: 'https://your-username.github.io/knitpkg/'

theme:
  name: 'material'
  language: 'en'
  features:
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - search.highlight
    - search.share
    - content.code.copy # Adds a copy button to code blocks
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      #primary: green
      #accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      #primary: blue
      #accent: deep orange
  icon:
    logo: fontawesome/solid/cubes
    # logo: assets/logo.png
    # favicon: assets/favicon.ico

nav:
  - Overview: index.md
  - Installation: installation.md
  - Core Concepts: 
    - Overview: concepts/overview.md
    - Manifest: concepts/manifest.md
#    - Packages: concepts/packages.md
#    - Projects: concepts/projects.md
#    - Registry: concepts/registry.md
#    - Git First: concepts/git-first.md
#  - User Guide:
#    - user-guide/index.md
#    - Creating Packages: user-guide/creating-packages.md
#    - Managing Dependencies: user-guide/managing-dependencies.md
#    - Package Registry: user-guide/package-registry.md
#    - Creating Projects: user-guide/creating-projects.md
#    - Project Settings: reference/project-settings.md
#    - Global Configuration: reference/global-configuration
  - Reference:
    - Manifest: reference/manifest.md
    - Version Ranges: reference/version-ranges.md
#    - KnitPkg Directives: reference/knitpkg-directives.md
#    - Project Layout: reference/project-layout.md
#    - CLI Reference: reference/cli.md
#    - Glossary: reference/glossary.md
#  - Troubleshooting & FAQ: troubleshooting.md
#  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list # Allows adding attributes to Markdown elements
  - md_in_html # Allows Markdown inside HTML blocks
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg