site_name: 'KnitPkg Documentation'
site_description: 'A modern package & project manager for MQL5/MQL4'
site_url: 'https://docs.knitpkg.dev/'

theme:
  name: 'material'
  language: 'en'
  features:
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode

nav:
  - Overview: index.md
  - Installation: installation.md
  - Core Concepts: 
    - Overview: concepts/overview.md
    - Manifest: concepts/manifest.md
    - KnitPkg Directives: concepts/directives.md
    - Install and Compile: concepts/install-and-compile.md
    - Include vs Flat Modes: concepts/include-vs-flat-modes.md
    - Projects vs Packages: concepts/projects-vs-packages.md
    - Composite Packages: concepts/composite-packages.md
    - Unit Tests: concepts/unit-tests.md
    - Registry: concepts/registry.md
    - Git First: concepts/git-first.md
    - Telemetry: concepts/telemetry.md
  - User Guide: 
    - Overview: user-guide/overview.md
    - Creating Packages: user-guide/creating-packages.md
    - Managing Dependencies: user-guide/managing-dependencies.md
    - Unit Tests: user-guide/unit-tests.md
    - Local Dependencies: user-guide/local-dependencies.md
    - Registry: user-guide/registry.md
#    - Creating Projects: user-guide/creating-projects.md
#    - Revision: user-guide/revisions.md
#    - Update: user-guide/update.md
#    - Settings: reference/settings.md
  - Reference:
    - Manifest: reference/manifest.md
    - Version Ranges: reference/version-ranges.md
    - CLI Reference: reference/cli.md
#    - Glossary: reference/glossary.md
#    - Troubleshooting & FAQ: troubleshooting.md
#    - Contributing: contributing.md
  - Terms of Service:
    - Telemetry: terms-of-service/telemetry.md
    - Registry: terms-of-service/registry.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.striphtml:
      strip_comments: true
      strip_js_on_attributes: false         